config/routes.rb
Bitqualize::Application.routes.draw do

	get 'welcome/login'
	get 'welcome/signup'
	get 'welcome/trace'
	get 'welcome/forgot'
	get 'welcome/resend'
	get 'welcome/change_password'
	get 'welcome/logout'
	get 'welcome/activate'
	
	post 'welcome/forgot_send'
	post 'welcome/create_user'
	post 'welcome/change_password'
	post 'welcome/login'
	post 'welcome/resend'
	
  get "welcome/index"
	root 'welcome#index'
	
end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/models/currency.rb
class Currency < ActiveRecord::Base
end

app/models/deposit.rb
class Deposit < ActiveRecord::Base
end

app/models/gacode.rb
class Gacode < ActiveRecord::Base
end

app/models/gauser.rb
class Gauser < ActiveRecord::Base
end

app/models/logindetail.rb
class Logindetail < ActiveRecord::Base
end

app/models/oldorder.rb
class Oldorder < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/orderexecution.rb
class Orderexecution < ActiveRecord::Base
end

app/models/parameter.rb
class Parameter < ActiveRecord::Base

	validates :paramname, :uniqueness => true

	def self.get_parameter(p_name)
		ret = Parameter.where(:paramname=>p_name).first
		return"" if ret.nil?
		return ret.paramvalue
	end

end

app/models/trxhistory.rb
class Trxhistory < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	validates :email, presence: true, uniqueness: true

	before_create do
		self.activation_token = Digest::SHA2.hexdigest("#{Time.now.to_i}-#{self.email}-#{rand}")
	end

	def self.activate(p_token)
		u = User.where(:activation_token => p_token).lock(true).first
		return 1002 if u.nil?
		u.activation_token = ""
		u.active_since = Time.now()
		u.save!
		return 0
	end

	def self.login(p_email,p_password,p_ip)
		u = User.where(:email=>p_email).first
		return 1001,nil if u.nil?
		u = u.authenticate(p_password)

		return 1001,nil if u.class != User
		return 0,u
	end

	def self.change_password(p_uid,p_password,p_password_confirmation,p_reset_token)
	end

	def self.reset_password(p_email)
		n_tries = 0
		ret = 9999
		begin
			u = User.where(:email=>p_email).lock(true).first
			return 1000 if u.nil?
			u.reset_token = User.hash_the_password(rand.to_s,u.salt,u.id,u.strength)

			#TODO: Send email with the token

			u.save!
			ret = 0
		rescue => e
			n_tries += 1
			sleep 0.05
			retry unless n_tries > 3
		end
		return ret
	end

end

app/models/withdrawal.rb
class Withdrawal < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	helper_method :current_user

	def error_to_text(p_error_number)
		r = case p_error_number
		when 1001 then 'Wrong email or password.'
		when 1002 then 'Unkown activation code.'
		when 1003 then 'Activation email was sent again.'
		when 1004 then 'Account is already activated.'
		when 1005 then 'Email does not exist.'
		when 1006 then 'IP address is blocked for 5 Minutes due to too frequent errors'
			else "ERROR"
		end
	end

	def current_user
		@current_user ||= User.where(:id=>session[:user_id]).first if session[:user_id]
	end

	def lock_if_brute_force_attack(p_function,p_ip)
		# Count how often a function is called within a minute, lock the IP if the threshold is exceeded

		# Thresholds
		p = {}
		p["RESEND"] = {:qty=>3, :lockduration=>600}
		p["LOGIN"] = {:qty=>3, :lockduration=>600}

		p_function.upcase!

		# Increase counter
		r = CACHE.get("ADMIN-BRUTE-#{p_function}-#{p_ip}")
		r = 0 if r.nil?
		r += 1

		# Save the data
		CACHE.set("ADMIN-BRUTE-#{p_function}-#{p_ip}",r,60)
		CACHE.set("ADMIN-LOCK-IP-#{p_ip}",p[p_function][:lockduration]) if r > p[p_function][:qty]
	end

	def ip_is_locked(p_ip)
		return true if CACHE.get("ADMIN-LOCK-IP-#{p_ip}")
		return false
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
	
	def login
		if request.post?
			en,u = User.login(params[:user][:email],params[:user][:password],request.remote_ip)
			if en == 0
				session[:user_id] = u.id
				redirect_to :root, :notice => "You are logged in"
			else
				@user = User.new
				@user.email = params[:user][:email]
				@user.errors[:email] = error_to_text(en)
				@user.errors[:password] = error_to_text(en)
				render :login
			end
		else
			@user = User.new
		end
	end

	def activate
		en = User.activate(params[:token])
		if en == 0
			redirect_to :welcome_login, :notice => "Your account has been activated"
		else
			redirect_to :root, :alert => "Unknown activation code"
		end
		
	end

	def logout
		reset_session
		@current_user = nil
		redirect_to :root, :notice => "You are logged out"
	end

	def signup
		@user = User.new
	end

	def trace
	end

	def forgot
		@user=User.new
	end

	def forgot_send
		en = User.reset_password(params[:user][:email])
		if en == 0
			redirect_to :root, :notice => "eMail send with reset instructions."
		else
			@user=User.new
			render :forgot
		end
	end

	def resend
		if request.post?
			lock_if_brute_force_attack('RESEND',request.remote_ip)
			redirect_to :root, :alert => error_to_text(1006) and return if ip_is_locked(request.remote_ip)
			
			u = User.where(:email=>params[:user][:email]).first
			if u
				logger.debug u.to_json
				if u.activation_token != "" && !u.activation_token.nil?
					MyMailer.activation_email(u.id).deliver
					redirect_to :root, :notice => error_to_text(1003)
				else
					redirect_to :root, :alert => error_to_text(1004)
				end
			else
				redirect_to :root, :alert => error_to_text(1005)
			end
		else
			@user = User.new
		end
	end

	def change_password
		if request.post?
			if @current_user
				@user = User.where(:id=>@current_user.id).first
			else
				@user = User.where(:reset_token=>params[:user][:reset_token]).first
			end

			@user.update_attributes(params.require(:user).permit(:password,:password_confirmation))
			#en = User.change_password(uid,params[:user][:password],params[:user][:password_confirmation],params[:user][:reset_token])
			redirect_to :root, :notice => "Password changed"
		else
			@user = User.new
			@user.reset_token = params[:reset_token]
		end
	end

	def create_user

		@user = User.new(params.require(:user).permit(:email,:password,:password_confirmation))
		if @user.save
			MyMailer.activation_email(@user.id).deliver
			redirect_to :root, :notice => "We have emailed you the account activation instructions."
		else
			render :signup
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def has_error(p_field,p_errors)
		return "has-error" unless p_errors[p_field] == []
		return ""
	end

	def has_error_text(p_field,p_errors)
		return p_errors[p_field][0]
		
	end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bitqualize</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body>
  <div id="wrap">
	<div class="navbar navbar-default navbar-static-top" role="navigation">
	  <div class="container">
		<div class="navbar-header">
		  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		  </button>
		  <a class="navbar-brand" href="#">Bitqualize</a>
		</div>
		<div class="navbar-collapse collapse">
		  <ul class="nav navbar-nav">
			<li><%=link_to 'Home', root_url()%></li>
		  </ul>
		  <ul class="nav navbar-nav navbar-right">
			<%if current_user%>
			  <li><%=link_to 'Logout',welcome_logout_url()%></li>
			<%else%>
			  <li><%=link_to 'Login',welcome_login_url()%></li>
			  <li><%=link_to 'Signup',welcome_signup_url()%></li>
			<%end%>
		  </ul>
		</div>
	  </div>
	</div>
	<div class="container">
	  <%if flash[:notice]%><div class="alert alert-success"><%=flash[:notice]%></div><%end%>
	  <%if flash[:warning]%><div class="alert alert-warning"><%=flash[:warning]%></div><%end%>
	  <%if flash[:alert]%><div class="alert alert-danger"><%=flash[:alert]%></div><%end%>
	  <%= yield %>
	</div>
  </div>

  <div id="footer">
	<div class="container">
	  <p class="text-muted credit">
		<%=link_to 'Developer\'s Trace', welcome_trace_url()%>
		Donations:  Devcoins (DVC): 16jsP4BQrkV6Vcm5jUE4u7gPpBM4XxbsSM
	  </p>
	</div>
  </div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-45587656-1', 'bitqualize.com');
  ga('send', 'pageview');
</script>
</body>
</html>

app/views/welcome/change_password.html.erb
<%= form_for @user, url: {controller: 'welcome', action: 'change_password'}, html: {class: 'form-signin form-horizontal'} do |f| %>

  <div class="well">
	<h2 class="form-signin-heading">Change password</h2>

	<%= f.hidden_field :reset_token, :value => @user.reset_token %>

	<div class="form-group <%=has_error(:password,@user.errors)%>">
	  <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
	  <div class="col-sm-10">
		<%=f.password_field :password, :class=>"form-control", :placeholder=>"Password", :type=>"password"%>
		<span class="help-block"><%=has_error_text(:password,@user.errors)%></span>
	  </div>
	</div>

	<div class="form-group <%=has_error(:password_confirmation,@user.errors)%>">
	  <label for="inputPassword3" class="col-sm-2 control-label">Repeat password</label>
	  <div class="col-sm-10">
		<%=f.password_field :password_confirmation, :class=>"form-control", :placeholder=>"Repeat password", :type=>"password"%>
		<span class="help-block"><%=has_error_text(:password_confirmation,@user.errors)%></span>
	  </div>
	</div>
	<%=f.submit "Change password",  class: 'btn btn-lg btn-primary btn-block'%>
  </div>
<%end%>

app/views/welcome/forgot.html.erb
<%= form_for @user, url: {controller: 'welcome', action: 'forgot_send', method: 'post'}, html: {class: 'form-signin form-horizontal'} do |f| %>
  <div class="well">
	<h2 class="form-signin-heading">Reset my password</h2>
	<div class="form-group <%=has_error(:email,@user.errors)%>">
	  <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
	  <div class="col-sm-10">
		<%=f.text_field :email, :class=>"form-control", :placeholder=>"Email", :type=>"email"%>
		<span class="help-block"><%=has_error_text(:email,@user.errors)%></span>
	  </div>
	</div>
	<button class="btn btn-lg btn-primary btn-block" type="submit">Reset</button>
  </div>
  <%=link_to "Login", welcome_login_url()%><br>
<%end%>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Coming soon</h1>
  <h3>Under active development</h3>
  <br>
  <p>
	This will become an open sourced Bitcoin Exchange that will return the majority of all fees collected back to its active users.
	In addition we will open source the complete project on <%=link_to 'Github','https://github.com/Bitqualize'%>. Apart from providing the full source code
	we'll be having open discussion on Bitcointalk on various sub-forums on the implementation architecture of the many aspects of an Exchange. Feel free to
	actively participate and contribute.
  </p>
  The initial scope of features
  <ul>
	<li>Buy and sell Bitcoins. The Exchange will be dealing only with Cryptocurrencies.</li>
	<li>API for information inquiry as well as trading</li>
	<li>Two factor authentication</li>
	<li>Basic graphing functionality</li>
	<li>Chat box</li>
	<li>Multi language capable</li>
	<li>Live update, pushing data to the user's browsers</li>
	<li>Regularly return a portion of the collected fees to the users</li>
  </ul>
</div>

app/views/welcome/login.html.erb
<%= form_for @user, url: {controller: 'welcome', action: 'login'}, html: {class: 'form-signin form-horizontal'} do |f| %>
  <div class="well">
	<h2 class="form-signin-heading">Please log in</h2>
	<div class="form-group <%=has_error(:email,@user.errors)%>">
	  <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
	  <div class="col-sm-10">
		<%=f.text_field :email, :class=>"form-control", :placeholder=>"Email", :type=>"email"%>
		<span class="help-block"><%=has_error_text(:email,@user.errors)%></span>
	  </div>
	</div>

	<div class="form-group <%=has_error(:password,@user.errors)%>">
	  <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
	  <div class="col-sm-10">
		<%=f.password_field :password, :class=>"form-control", :placeholder=>"Password", :type=>"password"%>
		<span class="help-block"><%=has_error_text(:password,@user.errors)%></span>
	  </div>
	</div>
	<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  </div>
  <%=link_to "Forgot my password", welcome_forgot_url()%><br>
  <%=link_to "Resend activtion email", welcome_resend_url()%>
<%end%>

app/views/welcome/resend.html.erb
<%= form_for @user, url: {controller: 'welcome', action: 'resend', :method=>'post'}, html: {class: 'form-signin form-horizontal'} do |f| %>
  <div class="well">
	<h2 class="form-signin-heading">Resend activation email</h2>
	<div class="form-group <%=has_error(:email,@user.errors)%>">
	  <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
	  <div class="col-sm-10">
		<%=f.text_field :email, :class=>"form-control", :placeholder=>"Email", :type=>"email"%>
		<span class="help-block"><%=has_error_text(:email,@user.errors)%></span>
	  </div>
	</div>
	<button class="btn btn-lg btn-primary btn-block" type="submit">Send</button>
  </div>
  <%=link_to "Login", welcome_login_url()%><br>
<%end%>

app/views/welcome/signup.html.erb
<%= form_for @user, url: {controller: 'welcome', action: 'create_user'}, html: {class: 'form-signin form-horizontal'} do |f| %>

  <div class="well">
	<h2 class="form-signin-heading">Please sign up</h2>

	<div class="form-group <%=has_error(:email,@user.errors)%>">
	  <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
	  <div class="col-sm-10">
		<%=f.text_field :email, :class=>"form-control", :placeholder=>"Email", :type=>"email"%>
		<span class="help-block"><%=has_error_text(:email,@user.errors)%></span>
	  </div>
	</div>

	<div class="form-group <%=has_error(:password,@user.errors)%>">
	  <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
	  <div class="col-sm-10">
		<%=f.password_field :password, :class=>"form-control", :placeholder=>"Password", :type=>"password"%>
		<span class="help-block"><%=has_error_text(:password,@user.errors)%></span>
	  </div>
	</div>

	<div class="form-group <%=has_error(:password_confirmation,@user.errors)%>">
	  <label for="inputPassword3" class="col-sm-2 control-label">Repeat password</label>
	  <div class="col-sm-10">
		<%=f.password_field :password_confirmation, :class=>"form-control", :placeholder=>"Repeat password", :type=>"password"%>
		<span class="help-block"><%=has_error_text(:password_confirmation,@user.errors)%></span>
	  </div>
	</div>
	<%=f.submit "Sign up",  class: 'btn btn-lg btn-primary btn-block'%>
  </div>
<%end%>

app/views/welcome/trace.html.erb
<h2>Developer's Trace</h2>

<ul>
  <li>9th November 2013:
	<ul>
	  <li>Domain registration, SSL certification, VPS setup, Bitcointalk/Twitter/Facebook accounts created</li>
	  <li>Empty application web site posted online</li>
	  <li>Coding the user login and registration pages and coding logic</li>
	</ul>
  </li>
</ul>